robosat/datasets.py

For #17. Need to think through either replacing the buffered tile dataset and moving its functionality into a transform or just keeping it as is.

Removes unused ImageDirectory dataset, see #17

---

robosat/tools/train.py

Closes: https://github.com/mapbox/robosat/issues/59

Remove resume flag in train script

---

config/model-unet.toml
robosat/tools/train.py

For https://github.com/mapbox/robosat/issues/58.

Uses Adam optimizer by default to simplify training setup, closes #58

---

robosat/osm/building.py
robosat/osm/core.py
robosat/osm/parking.py

For #69. A closed way can be made up of two times the same node.
We need at least four nodes in a closed way for a polygon.

Discards closed ways which are not valid polygons, closes #69

---

README.md
robosat/utils.py

Fixes https://github.com/mapbox/robosat/issues/62
This allows using matplotlib module without having the user the set it via the env variables.
cc @bkowshik @daniel-j-h

set AGG backend in the script

---

README.md

Clarifies configuration templates in readme, closes #63

---

README.md

Adds notes about using a virtualenv to the readme, closes #83 and #82

---

robosat/features/parking.py

For #90. Splitting this off of https://github.com/mapbox/robosat/pull/64 to get it into master asap already.

Makes sure there is a contour hierarchy in post-processing, closes #90

---

.travis.yml
README.md
docker/Dockerfile.cpu
docker/Dockerfile.gpu

Dockerfiles for CPU as well as GPU images.

Adds Dockerfiles for CPUs as well as GPUs, closes #29

---

robosat/tools/merge.py

Address issue #103 
In 'merge.py' we need to check shapely object's class before doing the orientation correction:
* if it's MultiPolygon, then we need to iterate over a MultiPolygon's polygons and manually orient them
* otherwise just orient the Polygon

Address issue #103

---

deps/requirements-lock.txt
deps/requirements.txt
robosat/metrics.py
robosat/tools/predict.py
robosat/tools/train.py

While training GPU spend lot of time idle, mainly for two reasons:
- Lot of time spend with CPU computation (scikit metrics)
- No enough workers to feed data 
This PR fix both.
And as a result, using several GPU for training become meaningful.

Train performances improvement

---

.gitignore
robosat/osm/road.py
robosat/tools/extract.py

I only take the lanes，oneway and width tags into consideration. In my opinions, the estimation of the road width should be function like y = k * x +b.

Add automatically generate a road training set based on OpenStreetMap

---

robosat/osm/road.py

For https://github.com/mapbox/robosat/issues/114. @neverwiredhouse @DragonEmperorG this should fix the issue when the osm data is bad for lane tags and width. Let me know if this works for you - thanks.

Guards against osm road data issues, resolves #114

---

config/dataset-parking.toml
config/model-unet.toml
robosat/log.py
robosat/losses.py
robosat/metrics.py
robosat/tools/export.py
robosat/tools/predict.py
robosat/tools/serve.py
robosat/tools/train.py

Hi,
Quite a few improvements in this PR:
- Add mIoU loss
- Add Lovasz loss
- Add a config parameter to allow to choose loss function among implemented ones
- Remove useless losses parameters (size_average and ignore_index)
- Add foreground IoU metric
- Add MCC metric
- Refactor and cleanup metric class
- Add resume training option 
- Add log training in text file, including hyperparameters 
As a consequence:
- Imply to add loss parameter in model config file
- .pth files already generated are not compliant anymore
Nota:
- Pixel accuracy metric wasn't that meaningful, i implement it, than remove it.
- mIoU and Lovasz both significantly improve semseg (rather than x entropy loss) 
Thanks in advance for the code review ^^

Losses and metrics improvements (mostly)

---

robosat/osm/building.py

Filters buildings based on location tags, closes #115

---

robosat/tools/__main__.py

Requires a sub-command from users, closes #102

---

robosat/tools/predict.py
robosat/tools/train.py

See #126. Disables worker processes communicating via shm by default.
https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader
> num_workers (int, optional) – how many subprocesses to use for data loading. 0 means that the data will be loaded in the main process. (default: 0)
cc @wboykinm @ocourtin

Disables shared-memory workers by default, see #126

---

robosat/osm/building.py
robosat/osm/core.py
robosat/osm/parking.py
robosat/osm/road.py
robosat/tools/extract.py

Allows users to specify the max number of features per batch.
Should help with https://github.com/mapbox/robosat/issues/143 and https://github.com/mapbox/robosat/issues/131.
@jacquestardie please merge

Implements batched feature extraction, resolves #120

---

robosat/metrics.py

cc @jacquestardie rebase merge please :bow:

Fixes potential div-by-zero in metrics

---

robosat/tools/predict.py
robosat/tools/train.py

Instead of bailing out only after the first (potentially expensive) epoch we now check this upfront.
cc @jacquestardie rebase merge please :bow:

Make sure there are tiles in the dataset upfront, resolves #141

---

robosat/unet.py

- https://pytorch.org/docs/stable/nn.html#torch.nn.functional.upsample
- https://pytorch.org/docs/stable/nn.html#torch.nn.functional.interpolate
cc @jacquestardie rebase merge please :bow:

Replaces deprecated upsample with interpolate in model

---

.travis.yml

https://travis-ci.org/mapbox/robosat/builds/539308137

Fixes travis trusty packages

---

robosat/features/core.py

For https://github.com/mapbox/robosat/issues/179

Fixes contour extraction, resolves #179

---

robosat/spatial/core.py

Fixed deprecated pyproj syntax
