robosat/tools/cover.py

See #24. Looks like the list of tile ids we generated was not unique before which causes some confusions.
Now `rs cover` generates a _unique_ list of tile ids.

Saves only unique tile ids in `rs cover`, closes #24

---

robosat/datasets.py
robosat/tools/predict.py
robosat/tools/serve.py
robosat/tools/templates/map.html

For #18. Let's the user pass in the slippy map tile size in tools.
This allows users to work e.g. with 256x256 tiles or 512x512 tiles.

Generalizes tile size across tools, closes #18

---

robosat/tools/merge.py

For #20. Uses a World Mollweide projection to preserve area information.
- https://en.wikipedia.org/wiki/Map_projection#Equal-area
- https://en.wikipedia.org/wiki/Mollweide_projection

Adds calculated area property to features in `rs merge`, closes #20

---

robosat/datasets.py
robosat/tools/train.py
robosat/transforms.py
tests/test_datasets.py

For #4. This changeset implements joint transformations and on top of that horizontal and vertical random flipping and multiple-of-90-degree rotations.
The design is as follows:
- We can not use `Compose` because it decouples transforming images from masks. But we need to keep them in sync: when we flip the image we also need to flip the mask.
- We add a new `JointCompose` callable running transformations on both: image, and mask at the same time. This allows us to implement transformations which can keep image and mask in sync.
- We implement `RandomHorizontalFlip` and `RanomVerticalFlip` as joint transformation working on an image and a mask at the same time. They take a probability and then either flip both image and mask, or none of them.

Implements joint transformations; closes #4

---

.gitignore
README.md
robosat/tools/__main__.py
robosat/tools/export.py
robosat/unet.py

For #38.
This changeset adds an ONNX exporter serializing the model and its weights into a GraphProto `.pb` file. This file no longer depends on PyTorch or the Python model class and can be used with tools from the ONNX ecosystem.
For example
```
model = onnx.load('buildings-z20-tanzania.pb')
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))
```
This will allow us to store and provide models which then can be used e.g. in Caffe2 or TensorFlow.

Adds ONNX model exporter; closes #38

---

robosat/tiles.py

For #47. Makes sure `z/x/y` are digits.
cc @maning

Makes sure Slippy Map dir follow z/x/y.ext with z,x,y digits, closes #47

---

robosat/tools/train.py

Horizontal flipping plus the four rotations by 0, 90, 180, 270 degrees are enough to result in all transformations we would get out of adding vertical flipping to the mix.
See https://en.wikipedia.org/wiki/Dihedral_group

Removes vertical flip: horizontal plus n*90 degree is equivalent

---

robosat/tools/train.py

Our slippy map dataset reads in tiles and sorts them by their [mercantile.Tile](http://mercantile.readthedocs.io/en/latest/api/mercantile.html#mercantile.Tile) (x, y, z) attributes.
https://github.com/mapbox/robosat/blob/5f35f2b16917a12ffce7fb8671ba27bbbd770a4c/robosat/datasets.py#L16-L39
This results in us training the model on neighboring strips of tiles when we don't shuffle the dataset. And currently we don't shuffle the dataset:
https://github.com/mapbox/robosat/blob/master/robosat/tools/train.py#L204-L205
This changeset shuffles the training dataset to get rid of any spatial dependence. The validation dataset can be in order since we only calculate the metrics at the end of an epoch and shuffling doesn't change anything here.
cc @maning

Shuffles the training dataset which is based on slippy map dir order

---

robosat/unet.py

The PyTorch tracing model exporter has an issue with shared weights / refs to layers, see
https://github.com/pytorch/pytorch/issues/8392
The workaround is to not store any refs to the resnet layers in the model itself. Instead we have to directly pull the input tensors through the resnet layers in the forward pass.
This will change the `.pth` file format. We could work around that by loading the serialized state dict in non-strict fashion in the export tool. But then we are opening up the door to letting actual errors going through.
Note:  we need to fix the FPN pull request in a similar way https://github.com/mapbox/robosat/pull/75
cc @bkowshik @maning

Works around internal PyTorch bug related to shared weights

---

robosat/tools/train.py

For #41.
We were only wrapping the model in a DataParallel module when on the CUDA path during training. In the unlikely event that folks want to train on CPUs we should at least make sure we can load the trained model again.

Wraps model in DataParallel during training on CPUs, closes #41

---

robosat/tools/merge.py

Closes: https://github.com/mapbox/robosat/issues/1
From https://shapely.readthedocs.io/en/stable/manual.html#shapely.geometry.polygon.orient
> **shapely.geometry.polygon.orient(polygon, sign=1.0)**
>
> Returns a properly oriented copy of the given polygon. The signed area of the result will have the given sign. A sign of 1.0 means that the coordinates of the product’s exterior ring will be oriented counter-clockwise.

Orient exterior ring of the polygon in counter-clockwise direction

---

robosat/datasets.py

Ref: https://github.com/mapbox/robosat/issues/100#issuecomment-411412939
> what we could do is change the wording from input and target to images and masks.

Use images and label instead of inputs and target

---

robosat/unet.py

With this fix, getting predictions with overlap % 32 != 0 will result in the following assertion.
```bash
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/app/robosat/robosat/tools/__main__.py", line 57, in <module>
args.func(args)
File "/app/robosat/robosat/tools/predict.py", line 82, in main
outputs = net(images)
File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
return self.module(*inputs[0], **kwargs[0])
File …
```

Assert image resolution has to be divisible by 32 for resnet

---

robosat/tools/train.py

`no_grad()` is available since pytorch 0.4.0 and prevents possible 'out of memory' errors during validation.

Added torch.no_grad() 

---

robosat/tools/rasterize.py
tests/tools/test_rasterize.py

For https://github.com/mapbox/robosat/issues/25. This changeset allows for batch-rasterization.
We can now run `rs rasterize` multiple times with multiple smaller (batched) GeoJSON files. And in the case of overlapping features (multiple GeoJSON files with features in the same tile) we now automatically merge the rasterized masks on the fly.
This will make pre-processing a bit easier on memory for folks.
@rory

Allows for batch-rasterization in `rs rasterize`, closes #25

---

docker/Dockerfile.cpu
docker/Dockerfile.gpu

At the moment users have to run the docker container with `/app/rs` as a command. Because robosat always goes through the `rs` wrapper and the docker containers only package up robosat it's a better idea to make it the default entrypoint.
- Before
`docker run --rm -it daniel-j-h/robosat:latest-cpu /app/rs extract ..`
- After
`docker run --rm -it daniel-j-h/robosat:latest-cpu extract ..`
Without sub-command we show the help printout.
<details>
```
docker build -t daniel-j-h/robosat:latest-cpu -f docker/Dockerfile.cpu .
docker run --rm -it daniel-j-h/robosat:latest-cpu
usage: ./rs [-h]  ...
optional arguments:
-h, --help  show this help message and exit
```
</details>
Supersedes https://github.com/mapbox/robosat/pull/140 - can be closed.
@jacquestardie please merge.

Uses `rs` command as default docker entrypoint

---

docker/Dockerfile.cpu
docker/Dockerfile.gpu

We use a pre-trained resnet in our encoder. The pre-trained weights are getting downloaded on-demand when we use the model for the first time. Usually this is fine when working without docker. With docker the container will get shut down after each command invokation which means we have to download the model weights every time we run a new `docker run .. train` command.
This changset instead pre-fetches the pre-trained weights and bakes them into the docker images at
```
~/.cache/torch/checkpoints/resnet50-19c8e357.pth
```
Then `docker run .. train` never has to download the weights on-demand, we are no longer dependent on external services, and everything works beautifully.
The downside is the docker image size will increase since the weights are ~100 MB. But because the nvidia docker …

Bakes pretrained model into docker image

---

docker/Dockerfile.cpu
docker/Dockerfile.gpu

In https://github.com/mapbox/robosat/pull/151 we pre-fetched the model's weights into the docker image which makes iterating on training faster. In contrast this changeset is about improving on iteration speed for code development.
- Removes unused dependencies to make the image smaller and the docker build process faster; pyosmium switched from Boost.Python to pybind11 and is bundling zlib and expat in their wheel by now. The rtree package only required the C libspatialindex shared object.
- Creates a separate layer for the pytorch wheel. Changes a couple times a year and is quite big, should get cached.
- Creates a separate layer only for our dependencies. Again they should change only every now and then, installing the python depdency packages is slow, and we should cache this.
- …

Splits docker build into cache-able layers for faster iteration

---

README.md

Turns out on Travis we install dependencies manually so we can run our tests. The first commit updates the dependencies. The second commit removes manual installation instructions from the readme - users should just use our pre-built docker images. And then shows example docker image usage instructions.
Preview: https://github.com/daniel-j-h/robosat/tree/update-readme#installation
cc @jacquestardie I think this is blocked by having up-to-date docker images (https://github.com/mapbox/robosat/issues/153) - which I just noticed we no longer have.

Updates readme to recommending our docker images

---

config/model-unet.toml
robosat/tools/train.py

pytorch's adam weight decay is l2 regularization and not what we want; until it is fixed and we get proper adamw we should just ignore it. See also https://www.fast.ai/2018/07/02/adam-weight-decay/

Removes adam's l2 regularization until fixed in pytorch#4429

---

Makefile
docker/Dockerfile.cpu
docker/Dockerfile.gpu

This changeset compiles Pillow-SIMD with AVX2 support for vectorized image operations (e.g. resize) and compiles against libjpeg-turbo for faster JPEG decoding.
The speedup is quite significant: the dataloaders can load, decode, and pre-process now like running a knife through butter. This takes considerable load off the CPU(s) and it's easier now to keep (potentially multiple) GPUs busy.
Note: downside is we require a machine with AVX2 support now. For GPU boxes this should be a given, and the 2015 laptop I'm writing this on comes with AVX2, too, so I'm happy to make it a default requirement.
Adding a convenient makefile in a second commit to make interaction with docker more pleasant.

Faster JPEG decoding and vectorized image transformations (requires AVX2 support)

---

docker/Dockerfile.cpu
docker/Dockerfile.gpu

Resolves #193. We compile Pillow-SIMD from source; if libwebp is not present we do not compile support for webp. This changeset fixes this mistake.
Pillow-SIMD compilation feature check: https://github.com/python-pillow/Pillow/blob/9b927155e693e0a337114422af46677991a010b0/setup.py#L659-L668
cc @oneOfThePeople

Compiles Pillow-SIMD with libwebp support, closes #193
